# Generated by Django 5.1.4 on 2025-03-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_branch_car_computer_ford_person_staff_delete_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='branch',
        ),
        migrations.DeleteModel(
            name='car',
        ),
        migrations.DeleteModel(
            name='Ford',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
