# Generated by Django 5.1.4 on 2025-03-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_staff_branch_delete_car_delete_ford_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
