# Generated by Django 5.1.4 on 2025-03-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_computer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='computer/'),
        ),
    ]
