# Generated by Django 5.1.4 on 2025-03-13 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_computer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('branchAddress', models.CharField(max_length=255)),
                ('telNo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('YearMade', models.IntegerField()),
                ('Image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Ford',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('YearMade', models.IntegerField()),
                ('Image', models.URLField()),
                ('Brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('hobby', models.CharField(choices=[('Swimming', 'Swimming'), ('Reading', 'Reading'), ('Biking', 'Biking'), ('Other', 'Other')], max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('language', models.CharField(choices=[('English', 'English'), ('Khmer', 'Khmer'), ('French', 'French'), ('Other', 'Other')], max_length=20)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='computer_images/'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='course.branch')),
            ],
        ),
    ]
